gestionAlmacenDemo/gestionAlmacen/Controllers/ProveedoresController.cs
using gestionAlmacen.Models;
using gestionAlmacen.Repositories.Categorias;
using gestionAlmacen.Repositories.Proveedores;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace gestionAlmacen.Controllers
{
    public class ProveedoresController : Controller
    {
        private readonly IProveedoresRepository _proveedoresRepository;

        public ProveedoresController(IProveedoresRepository proveedoresRepository)
        {
            _proveedoresRepository = proveedoresRepository;

        }


        // GET: ProveedoresController
        public ActionResult Index()
        {
            return View(_proveedoresRepository.GetAll());
        }

        // GET: ProveedoresController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProveedoresController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProveedoresController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MProveedores mProveedores)
        {
            try
            {
                _proveedoresRepository.Add(mProveedores);

                TempData["message"] = "Dato guardado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(mProveedores);
            }
        }

        // GET: ProveedoresController/Edit/5
        public ActionResult Edit(int id)
        {
            var mProveedores = _proveedoresRepository.GetById(id);

            if (mProveedores == null)
            {
                return NotFound();
            }

            return View(mProveedores);
        }

        // POST: ProveedoresController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MProveedores mProveedores)
        {
            try
            {
                _proveedoresRepository.Edit(mProveedores);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(mProveedores);
            }
        }

        // GET: ProveedoresController/Delete/5
        public ActionResult Delete(int id)
        {
            var mProveedores = _proveedoresRepository.GetById(id);

            if (mProveedores == null)
            {
                return NotFound();
            }

            return View(mProveedores);
        }

        // POST: ProveedoresController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MProveedores mProveedores)
        {
            try
            {
                _proveedoresRepository.Delete(mProveedores.ID_Proveedor);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = "Error al eliminar el cliente: " + ex.Message;
                ViewBag.errror = ex.Message;
                return View(mProveedores);
            }
        }
    }
}

gestionAlmacenDemo/gestionAlmacen/Views/Proveedores/Create.cshtml
@model gestionAlmacen.Models.MProveedores

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MProveedores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @*  <div class="form-group">
                <label asp-for="ID_Proveedor" class="control-label"></label>
                <input asp-for="ID_Proveedor" class="form-control" />
                <span asp-validation-for="ID_Proveedor" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoElectronico" class="control-label"></label>
                <input asp-for="CorreoElectronico" class="form-control" />
                <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

gestionAlmacenDemo/gestionAlmacen/Views/Proveedores/Delete.cshtml
@model gestionAlmacen.Models.MProveedores

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MProveedores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID_Proveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID_Proveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoElectronico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoElectronico)
        </dd>
    </dl>
    
    @* <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form> *@

    <form asp-action="Delete" method="post">
        @Html.HiddenFor(model => model.ID_Proveedor)
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Cancelar</a>
    </form>
</div>

gestionAlmacenDemo/gestionAlmacen/Views/Proveedores/Edit.cshtml
@model gestionAlmacen.Models.MProveedores

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MProveedores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @*  <div class="form-group">
                <label asp-for="ID_Proveedor" class="control-label"></label>
                <input asp-for="ID_Proveedor" class="form-control" />
                <span asp-validation-for="ID_Proveedor" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="hidden" asp-for="ID_Proveedor" />
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoElectronico" class="control-label"></label>
                <input asp-for="CorreoElectronico" class="form-control" />
                <span asp-validation-for="CorreoElectronico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

gestionAlmacenDemo/gestionAlmacen/Views/Proveedores/Index.cshtml
@model IEnumerable<gestionAlmacen.Models.MProveedores>

@{
    ViewData["Title"] = "Index";
}

<h1>Proveedores</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Crear nuevo proveedor</a>
</p>

@if (TempData["message"] != null)
{
    <div class="alert alert-primary" role="alert">
        @TempData["message"]
    </div>
}
<table class="table table-bordered table-striped table-responsive mt-2" id="ProveedoresTables">
    <thead>
        <tr>
            @* <th>
                @Html.DisplayNameFor(model => model.ID_Proveedor)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoElectronico)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @* <td>
                @Html.DisplayFor(modelItem => item.ID_Proveedor)
            </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoElectronico)
            </td>
            <td>

                    <a asp-controller="Proveedores"
                       asp-action="Edit"
                       asp-route-id="@item.ID_Proveedor"
                       class="btn btn-primary">
                        Editar
                    </a>

                    <a asp-action="Delete"
                       asp-route-id="@item.ID_Proveedor"
                       class="btn btn-danger">
                        Eliminar
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts {

    <script>
        $(document).ready(function () {
            $("#ProveedoresTables").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'csv', 'pdf', 'excel'
                ],
                columnDefs: [
                    {
                        target: 4,
                        orderable: false,
                        searchable: false
                    }
                ],
                // language: {
                //     url: '//cdn.datatables.net/plug-ins/2.0.3/i18n/es-ES.json'
                // }
            });
        })
    </script>
}