gestionAlmacenDemo/gestionAlmacen/Controllers/CategoriasController.cs
//using AspNetCore;
using gestionAlmacen.Models;
using gestionAlmacen.Repositories.Categorias;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace gestionAlmacen.Controllers
{

    public class CategoriasController : Controller
    {
        private readonly ICategoriasRepository _categoriasRepository;

            public CategoriasController(ICategoriasRepository categoriasRepository) 
            {
                _categoriasRepository = categoriasRepository;
                
            }
            
        
        //Se muestra la vista del index del cliente
        public ActionResult Index()
        {
            return View(_categoriasRepository.GetAll());
        }

        // 
        public ActionResult Details(int id)
        {
            return View();
        }


        //Se muestra la vista agregar un nuevo cliente
        public ActionResult Create()
        {
            return View();
        }

        // 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MCategorias mCategorias)
        {
            try
            {
                _categoriasRepository.Add(mCategorias);

                TempData["message"] = "Dato guardado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(mCategorias);
            }
        }

        [HttpGet]
        //Se muestra la vista editar del cliente
        public ActionResult Edit(int id)
        {
            var mCategorias = _categoriasRepository.GetById(id);

            if (mCategorias == null)
            {
                return NotFound();
            }

            return View(mCategorias);
        }

        // 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MCategorias mCategorias)
        {
            try
            {
                _categoriasRepository.Edit(mCategorias);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(mCategorias);
            }
        }

        //Se muestra la vista eliminar del cliente
        public ActionResult Delete(int id)
        {
            var mCategorias = _categoriasRepository.GetById(id);

            if (mCategorias == null)
            {
                return NotFound();
            }

            return View(mCategorias);
        }

        // 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MCategorias mCategorias)
        {
            try
            {
                _categoriasRepository.Delete(mCategorias.ID_Categoria);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = "Error al eliminar el cliente: " + ex.Message;
                ViewBag.errror = ex.Message;
                return View(mCategorias);
            }
        }
    }
}

gestionAlmacenDemo/gestionAlmacen/Controllers/ClientesController.cs
using gestionAlmacen.Models; 
///
using gestionAlmacen.Repositories.Clientes;
using gestionAlmacen.Services.Email;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;

namespace gestionAlmacen.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IClientesRepository _clientesRepository;
        private readonly IEmailService _emailService;

        public ClientesController(IClientesRepository clientesRepository, IEmailService emailService)
        {
            _clientesRepository = clientesRepository;
            _emailService = emailService;
        }

        //Se muestra la vista index del cliente
        public ActionResult Index()
        {
            return View(_clientesRepository.GetAll());
        }

        //
        public ActionResult Details(int id)
        {
            return View();
        }

        //Muestra la vista para agregar un nuevo cliente
        public ActionResult Create()
        {
            return View();
        }

        //Añade el cliente nuevo
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MClientes mClientes)
        {
            try
            {
                _clientesRepository.Add(mClientes);

                TempData["message"] = "Datos guardados exitosamente";

                string email = "equipo4calculadora@gmail.com";
                string subject = "Bienvenido al sistema";
                string body = "Bienvenido al sistema de gestion de almacen " + mClientes.Nombre;

                _emailService.SendEmail(email, mClientes.Nombre, subject, body);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(mClientes);
            }
        }

        //Muestra la vista de editar Cliente
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var mClientes = _clientesRepository.GetById(id);

            if (mClientes == null)
            {
                return NotFound();
            }

            return View(mClientes);
        }

        //Se edita el cliente
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MClientes mClientes)
        {
            try
            {
                _clientesRepository.Edit(mClientes);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(mClientes);
            }
        }

        //Muestra la vista de elminar
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var mClientes = _clientesRepository.GetById(id);

            if (mClientes == null)
            {
                return NotFound();
            }

            return View(mClientes);
        }

        //Se elimina el cliente
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MClientes mClientes)
        {
            try
            {
                _clientesRepository.Delete(mClientes.ID_Cliente);

                TempData["message"] = "Dato eliminado exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = "Error al eliminar el cliente: " + ex.Message;
                ViewBag.errror = ex.Message;
                return View(mClientes);
            }
        }
    }
}

gestionAlmacenDemo/gestionAlmacen/Controllers/ProductosController.cs
using gestionAlmacen.Models;
using gestionAlmacen.Repositories.Productos;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace gestionAlmacen.Controllers
{
    public class ProductosController : Controller
    {
        private readonly IProductosRepository _productosRepository;

        public ProductosController(IProductosRepository productosRepository)
        {
            _productosRepository = productosRepository;
        }

        // GET: ProductosController
        public ActionResult Index()
        {
            return View(_productosRepository.GetAll());
        }

        // GET: ProductosController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MProductos mProductos)
        {
            try
            {
                _productosRepository.Add(mProductos);

                TempData["message"] = "Datos guardados exitosamente";

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(mProductos);
            }
        }

        // GET: ProductosController/Edit/5
        public ActionResult Edit(int id)
        {
            var mProductos = _productosRepository.GetById(id);

            if(mProductos == null)
            {
                return NotFound();
            }

            return View(mProductos);
        }

        // POST: ProductosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MProductos mProductos)
        {
            try
            {
                _productosRepository.Edit(mProductos);

                TempData["message"] = "Datos editados correctamente";

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                return View(mProductos);
            }
        }


        // GET: ProductosController/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var mProductos = _productosRepository.GetById(id);

            if (mProductos == null)
            {
                return NotFound();
            }

            return View(mProductos);
        }

        // POST: ProductosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {

            try
            {
                _productosRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Delete), new { ID_Producto = id, error = true });

            }


            ////try
            ////{
            ////    _productosRepository.Delete(mProductos.ID_Producto);

            ////    TempData["message"] = "Dato eliminado exitosamente";

            ////    return RedirectToAction(nameof(Index));
            ////}
            ////catch (Exception ex)
            ////{
            ////    TempData["message"] = "Error al eliminar el cliente: " + ex.Message;
            ////    ViewBag.errror = ex.Message;
            ////    return View(mProductos);
            ////}
        }

    }
}

gestionAlmacenDemo/gestionAlmacen/Controllers/VentasController.cs
using gestionAlmacen.Models;
using gestionAlmacen.Repositories.Ventas;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace gestionAlmacen.Controllers
{
    public class VentasController : Controller
    {
        private readonly IVentasRepository _ventasRepository;
        private SelectList _clientesList;

        public VentasController(IVentasRepository ventasRepository)
        {
            _ventasRepository = ventasRepository;
            //El SelectList solo acepta dos parametros
            _clientesList = new SelectList(
                                        _ventasRepository.GetAllClientes(),
                                        nameof(MClientes.ID_Cliente),
                                        nameof(MClientes.Nombre)
                                        //nameof(MClientes.Direccion),
                                        //nameof(MClientes.Telefono),                                      
                                        //nameof(MClientes.CorreoElectronico)
                                    );
        }

        // GET: VentasController
        public ActionResult Index()
        {
            return View(_ventasRepository.GetAll());
        }

        // GET: VentasController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VentasController/Create
        
        public ActionResult Create()
        {
            //Es la carpeta de los repositorios
            ViewBag.Clientes = _clientesList;

            return View();
        }

        // POST: VentasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MVentas mVentas)
        {
            try
            {
                _ventasRepository.Add(mVentas);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ViewBag.Clientes = _clientesList;
                return View(mVentas);
            }
        }

        // GET: VentasController/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var mVentas = _ventasRepository.GetById(id);

            _clientesList = new SelectList(
                                        _ventasRepository.GetAllClientes(),
                                        nameof(MClientes.ID_Cliente),
                                        nameof(MClientes.Nombre),
                                        mVentas?.MClientes?.ID_Cliente
                                    );

            ViewBag.Clientes = _clientesList;

            return View(mVentas);
        }

        // POST: VentasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MVentas mVentas)
        {
            try
            {
                _ventasRepository.Edit(mVentas);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.Clientes = _clientesList;
                return View(mVentas);
            }
        }

        // GET: VentasController/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var mVentas = _ventasRepository.GetById(id);

            if (mVentas == null)
            {
                return NotFound();
            }

            return View(mVentas);
        }

        // POST: VentasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _ventasRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Delete), new { ID_Venta = id, error = true });

            }
        }
    }
}

gestionAlmacenDemo/gestionAlmacen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - gestionAlmacen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/gestionAlmacen.styles.css" asp-append-version="true" />

    <link href="https://cdn.datatables.net/2.0.3/css/dataTables.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/3.0.1/css/buttons.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/3.0.1/css/responsive.dataTables.min.css" rel="stylesheet">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">gestionAlmacen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">



                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Tablas
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                                @* <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li> *@

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Index">Ventas</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="DetallesVentas" asp-action="Index">Detalle de ventas</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Productos" asp-action="Index">Productos</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">Categorias</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Proveedores" asp-action="Index">Proveedores</a>
                                </li>
                            </ul>
                        </li>

                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Index">Ventas</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DetallesVentas" asp-action="Index">Detalle de ventas</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Proveedores" asp-action="Index">Proveedores</a>
                        </li> *@

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - gestionAlmacen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.1/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.1/js/dataTables.responsive.min.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>