gestionAlmacenDemo/gestionAlmacen/Controllers/DetallesVentasController.cs
using gestionAlmacen.Models;
using gestionAlmacen.Repositories.DetalleVenta;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NuGet.Protocol.Plugins;

namespace gestionAlmacen.Controllers
{
    public class DetallesVentasController : Controller
    {
        private readonly IDetalleVentasRepository _detatalleVentaRepository;
        private SelectList _productosList;

        //talvez
        //private SelectList _ventasList;

        public DetallesVentasController(IDetalleVentasRepository detatalleVentaRepository)
        {
            _detatalleVentaRepository = detatalleVentaRepository;
            _productosList = new SelectList(
                _detatalleVentaRepository.GetAllProductos(),
                nameof(MProductos.ID_Producto),
                nameof(MProductos.Nombre)
                );

            //// Cargar los ID_Venta para la vista
            //ViewBag.Ventas = new SelectList(
            //    _detatalleVentaRepository.GetAllVentas(),
            //    nameof(MVentas.ID_Venta),
            //    nameof(MVentas.ID_Venta)
            //);


        }

        public ActionResult Index()
        {
            return View(_detatalleVentaRepository.GetAll());
        }

        // GET: FacultyController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FacultyController/Create
        public ActionResult Create()
        {
            ViewBag.Productos = _productosList;

            //Talvez
            //ViewBag.Ventas = _ventasList;

            return View();
        }

        // POST: FacultyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(MDetalle_Venta detalle_Venta)
        {
            try
            {
                _detatalleVentaRepository.Add(detalle_Venta);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Productos = _productosList;

                return View(detalle_Venta);
            }
        }

        // GET: FacultyController/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var detalle_Venta = _detatalleVentaRepository.GetById(id);

            _productosList = new SelectList(
                                _detatalleVentaRepository.GetAllProductos(),
                                nameof(MProductos.ID_Producto),
                                nameof(MProductos.Nombre),
                                // mProductos es del modelo el ultimo
                                detalle_Venta?.mProductos?.ID_Producto

                                   );

            ViewBag.Productos = _productosList;

            return View(detalle_Venta);
        }

        // POST: FacultyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MDetalle_Venta detalle_Venta)
        {
            try
            {
                _detatalleVentaRepository.Edit(detalle_Venta);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.Productos = _productosList;

                return View(detalle_Venta);
            }
        }

        // GET: FacultyController/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var detalleVenta = _detatalleVentaRepository.GetById(id);

            if (detalleVenta == null)
            {
                return NotFound();
            }

            return View(detalleVenta);
        }

        // POST: FacultyController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                _detatalleVentaRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Delete), new { ID_Detalle = id, error = true });
            }
        }
    }
}

gestionAlmacenDemo/gestionAlmacen/Views/DetallesVentas/Create.cshtml
@model gestionAlmacen.Models.MDetalle_Venta

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MDetalle_Venta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <input type="hidden" asp-for="ID_Detalle" />
                <label asp-for="ID_Detalle" class="control-label"></label>
                <input asp-for="ID_Detalle" class="form-control" />
                <span asp-validation-for="ID_Detalle" class="text-danger"></span>
            </div> *@

            <div class="form-group">
                <label asp-for="ID_Venta" class="control-label"></label>
                <input asp-for="ID_Venta" class="form-control" />
                <span asp-validation-for="ID_Venta" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ID_Producto" class="control-label"></label>

                <select asp-for="ID_Producto"
                        asp-items="@ViewBag.Productos"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>

                <span asp-validation-for="ID_Producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio_Unitario" class="control-label"></label>
                <input asp-for="Precio_Unitario" class="form-control" />
                <span asp-validation-for="Precio_Unitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subtotal" class="control-label"></label>
                <input asp-for="Subtotal" class="form-control" />
                <span asp-validation-for="Subtotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Impuesto" class="control-label"></label>
                <input asp-for="Impuesto" class="form-control" />
                <span asp-validation-for="Impuesto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

gestionAlmacenDemo/gestionAlmacen/Views/DetallesVentas/Delete.cshtml
@model gestionAlmacen.Models.MDetalle_Venta

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MDetalle_Venta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID_Detalle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID_Detalle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID_Venta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID_Venta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID_Producto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID_Producto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio_Unitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio_Unitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subtotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subtotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Impuesto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Impuesto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

gestionAlmacenDemo/gestionAlmacen/Views/DetallesVentas/Edit.cshtml
@model gestionAlmacen.Models.MDetalle_Venta

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MDetalle_Venta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <input type="hidden" asp-for="ID_Detalle" />
                <label asp-for="ID_Detalle" class="control-label"></label>
                <input asp-for="ID_Detalle" class="form-control" />
                <span asp-validation-for="ID_Detalle" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="hidden" asp-for="ID_Detalle" />
                <label asp-for="ID_Venta" class="control-label"></label>
                <input asp-for="ID_Venta" class="form-control" />
                <span asp-validation-for="ID_Venta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ID_Producto" class="control-label"></label>

                <select asp-for="ID_Producto"
                        asp-items="@ViewBag.Productos"
                        class="form-select">
                    <option value="">Seleccione</option>
                </select>

                <span asp-validation-for="ID_Producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio_Unitario" class="control-label"></label>
                <input asp-for="Precio_Unitario" class="form-control" />
                <span asp-validation-for="Precio_Unitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subtotal" class="control-label"></label>
                <input asp-for="Subtotal" class="form-control" />
                <span asp-validation-for="Subtotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Impuesto" class="control-label"></label>
                <input asp-for="Impuesto" class="form-control" />
                <span asp-validation-for="Impuesto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

gestionAlmacenDemo/gestionAlmacen/Views/DetallesVentas/Index.cshtml
@model IEnumerable<gestionAlmacen.Models.MDetalle_Venta>

@{
    ViewData["Title"] = "Index";
}

<h1>Detalle venta</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Crear nueva venta</a>
</p>

@if (TempData["message"] != null)
{
    <div class="alert alert-primary" role="alert">
        @TempData["message"]
    </div>
}
<table class="table table-bordered table-striped table-responsive mt-2" id="Detalle_ventaTables">
    <thead>
        <tr>
            @* <th>
                @Html.DisplayNameFor(model => model.ID_Detalle)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.ID_Venta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.mProductos.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio_Unitario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subtotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Impuesto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @* <td>
                @Html.DisplayFor(modelItem => item.ID_Detalle)
            </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.ID_Venta)
            </td>
                <td>
                    @item.mProductos?.Nombre
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio_Unitario)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subtotal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Impuesto)
                </td>
            <td>

                    <a asp-controller="DetallesVentas"
                       asp-action="Edit"
                       asp-route-id="@item.ID_Detalle"
                       class="btn btn-primary">
                        Editar
                    </a>

                    <a asp-action="Delete"
                       asp-route-id="@item.ID_Detalle"
                       class="btn btn-danger">
                        Eliminar
                    </a>
               
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts {

    <script>
        $(document).ready(function () {
            $("#Detalle_ventaTables").DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'csv', 'pdf', 'excel'
                ],
                columnDefs: [
                    {
                        target: 6,
                        orderable: false,
                        searchable: false
                    }
                ],
                // language: {
                //     url: '//cdn.datatables.net/plug-ins/2.0.3/i18n/es-ES.json'
                // }
            });
        })
    </script>
}